# Generated by Django 3.2.5 on 2021-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_comment',
            field=models.CharField(default='Hola', max_length=100),
        ),
    ]
